name: forms
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.16.2"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  reactive_forms:
    git:
      url: https://github.com/innFactory/reactive_forms.git
      ref: d927ca9ba10ca038c90562bfb386813fdab78ef9
  freezed_annotation: ^2.2.0
  keyboard_actions: ^4.2.0
  flutter_hooks: ^0.20.3

dev_dependencies:
  build_runner: any
  freezed: ^2.3.4
