name: sync
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  core:
    path: ../core
  database:
    path: ../database
  todo:
    path: ../todo
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  synchronized: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
