name: fluter-todo-starter

sdkPath: .fvm/flutter_sdk

packages:
  - packages/*

scripts:
  init:
    run: |
      melos bootstrap
      melos run codegen --no-select

  build:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner

  build:watch:
    exec: flutter pub run build_runner watch --delete-conflicting-outputs
    select-package:
      depends-on: build_runner

  check:format:
    run: melos exec -c 5 --fail-fast -- dart format --set-exit-if-changed .

  check:analyze:
    run: melos exec -c 5 --fail-fast -- flutter analyze

  flavor:build:
    exec: flutter pub run flutter_flavorizr
    select-package:
      scope: app

  flavor:icons:
    exec: dart run tools/icons.dart
    select-package:
      scope: app

  clean:
    run: melos exec -c 6 -- flutter clean
    description: Clean Flutter packages

  codegen:
    run: |
      melos exec -c 6 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run code generation using build_runner
    select-package:
      depends-on: "build_runner"
