name: network_info
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  connectivity_plus: ^2.3.6
  rxdart: ^0.27.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
