name: network_info
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  connectivity_plus: ^5.0.0
  rxdart: ^0.27.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
