name: kv_store
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  core_dev:
    path: ../core_dev
