name: database
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  sync:
    path: ../sync
  todo:
    path: ../todo

  shared_preferences: ^2.0.18
  path_provider: ^2.0.11
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  drift_dev: ^2.8.1
