name: database
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  sync:
    path: ../sync
  todo:
    path: ../todo

  path_provider: ^2.0.11
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.17
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  drift_dev: ^2.8.1
