name: database
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  sync:
    path: ../sync

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.0.18
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  isar_generator: ^3.1.0+1
