name: api_client
version: 1.0.0
description: OpenAPI API client
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: "^5.0.0"
  json_annotation: "^4.8.1"
  core:
    path: ../core

dev_dependencies:
  build_runner: any
  json_serializable: "^6.1.5"
  test: ^1.16.0
