name: todo
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  sync:
    path: ../sync
  database:
    path: ../database
  api:
    path: ../api
  network_info:
    path: ../network_info
  forms:
    path: ../forms

  freezed_annotation: ^2.2.0
  reactive_forms:
    git:
      url: git@github.com:innFactory/reactive_forms.git
      ref: 3fe9b4d1ada3169498f0244c9d4c251f01dcb325

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
