name: todo
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  sync:
    path: ../sync
  database:
    path: ../database
  api:
    path: ../api
  network_info:
    path: ../network_info
  forms:
    path: ../forms

  freezed_annotation: ^2.2.0
  reactive_forms:
    git:
      url: https://github.com/innFactory/reactive_forms.git
      ref: d927ca9ba10ca038c90562bfb386813fdab78ef9

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
