name: api
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  api_client:
    path: ../api-client
  todo:
    path: ../todo
  network_info:
    path: ../network_info

  dio: ^5.0.1
  dio_smart_retry: ^5.0.0
  freezed_annotation: ^2.2.0
  freezed: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  mocktail: ^0.3.0
