name: core
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.17.2
  clock: ^1.1.1
  fpdart: ^0.6.0
  hooks_riverpod: ^2.4.3
  kt_dart: ^1.1.0
  meta: ^1.9.1
  logger: ^2.0.2+1
  lint_factory: ^3.7.0
  time: ^2.1.3
  intl: ^0.19.0
  flutter_i18n: ^0.35.1
  uuid: ^4.1.0
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
