name: core
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.17.0
  clock: ^1.1.1
  fpdart: ^0.5.0
  hooks_riverpod: ^2.3.5
  kt_dart: ^1.1.0
  meta: ^1.8.0
  logger: ^1.3.0
  lint_factory: ^3.7.0
  time: ^2.1.3
  intl: ^0.18.0
  flutter_i18n: ^0.33.0
  uuid: ^3.0.7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
