name: admin_utils
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  drift: ^2.12.1
  drift_db_viewer: ^2.0.0
  shake: ^2.2.0
  flutter_hooks: ^0.20.3
  equatable: ^2.0.5

dev_dependencies:
  build_runner: any
  auto_route_generator: ^7.0.0
  lint_factory: ^3.7.0
