name: admin_utils
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.3.2
  drift: ^2.8.0
  drift_db_viewer: ^2.0.0
  shake: ^2.2.0
  flutter_hooks: ^0.18.6
  equatable: ^2.0.5

dev_dependencies:
  build_runner: any
  auto_route_generator: ^7.0.0
  lint_factory: ^3.7.0
